version: '3'

services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.361.1-1
    container_name: jenkins-blueocean
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    ports:
      - "49000:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - "$HOME:/home"
    restart: on-failure

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
